 route:
     receiver: 'slack'

 receivers:
     - name: 'slack'
       slack_configs:
           - send_resolved: true
             username: 'ZCE-AlertManager'
             channel: '#zce-alerts'
             api_url: 'null'