# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

    static_configs:
        - targets: ['10.89.52.81:8080']
          labels:
            name: 'Barix_Low'
        - targets: ['10.89.52.90:8080']
          labels:
            name: 'Barix_High'

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
      
    static_configs: #edge devices
          - targets: ['10.89.52.81:9100']
            labels:
              name: 'Barix 1 (L)'
          - targets: ['10.89.52.90:9100'] 
            labels:
              name: 'Barix 2 (H)'
          - targets: ['10.89.52.110:9100']
            labels:
              name: 'ASI 1'
          - targets: ['10.89.52.191:9100']
            labels:
              name: 'ASI 2'          
          - targets: ['10.89.52.86:9092']
            labels:
              name: 'Sound4 1'
          - targets: ['10.89.52.182:9092']
            labels:
              name: 'Sound4 2'
          - targets: ['10.89.52.95:9100']
            labels:
              name: 'Telos 1'